import type { Metadata, Viewport } from "next";
import { Inter, JetBrains_Mono } from "next/font/google";
import "./globals.css";

const inter = Inter({
  variable: "--font-sans",
  subsets: ["latin"],
  display: "swap",
});

const jetbrainsMono = JetBrains_Mono({
  variable: "--font-mono",
  subsets: ["latin"],
  display: "swap",
});

// Static URL - hardcoded for proper crawler indexing (no env vars for SEO metadata)
const SITE_URL = "https://geonarrator.studio";
const SITE_NAME = "GeoNarrator Studio";
const SITE_TITLE = "GeoNarrator Studio | 3D Scrollytelling Map Editor";
const SITE_DESCRIPTION = "Create stunning 3D map-based stories without writing code. A no-code scrollytelling editor powered by Mapbox GL with cinematic camera controls, drag-and-drop scene management, and beautiful animations. Perfect for journalists, educators, and storytellers.";

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 5,
  userScalable: true,
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#f8fafc" },
    { media: "(prefers-color-scheme: dark)", color: "#020617" },
  ],
  colorScheme: "dark light",
};

export const metadata: Metadata = {
  // Basic metadata
  title: {
    default: SITE_TITLE,
    template: `%s | ${SITE_NAME}`,
  },
  description: SITE_DESCRIPTION,
  keywords: [
    "scrollytelling",
    "scrollytelling tool",
    "mapbox",
    "mapbox gl",
    "3D maps",
    "3D map editor",
    "storytelling",
    "geographic visualization",
    "no-code",
    "no-code map editor",
    "map editor",
    "interactive maps",
    "data visualization",
    "journalism",
    "narrative maps",
    "story maps",
    "map storytelling",
    "geographic storytelling",
    "visual storytelling",
    "data journalism",
    "interactive storytelling",
    "map animation",
    "cinematic maps",
    "fly-through maps",
    "location-based stories",
    "geospatial visualization",
  ],

  // Authors and ownership
  authors: [
    { name: "GeoNarrator Studio", url: SITE_URL },
  ],
  creator: SITE_NAME,
  publisher: SITE_NAME,

  // Robots and indexing
  robots: {
    index: true,
    follow: true,
    nocache: false,
    googleBot: {
      index: true,
      follow: true,
      noimageindex: false,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },

  // Open Graph (Facebook, LinkedIn, etc.)
  // Images are auto-generated by opengraph-image.tsx
  openGraph: {
    type: "website",
    locale: "en_US",
    alternateLocale: ["es_ES", "pt_BR", "fr_FR", "de_DE"],
    url: SITE_URL,
    siteName: SITE_NAME,
    title: SITE_TITLE,
    description: SITE_DESCRIPTION,
  },

  // Twitter Card
  // Image is auto-generated by twitter-image.tsx
  twitter: {
    card: "summary_large_image",
    site: "@geonarrator",
    creator: "@geonarrator",
    title: SITE_TITLE,
    description: SITE_DESCRIPTION,
  },

  // App metadata
  applicationName: SITE_NAME,
  category: "productivity",
  classification: "Web Application",

  // Verification - Add your codes here when you have them
  // verification: {
  //   google: "your-google-verification-code",
  //   yandex: "your-yandex-verification-code",
  // },

  // Additional metadata
  referrer: "origin-when-cross-origin",
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },

  // Manifest for PWA
  manifest: "/manifest.json",

  // Icons - auto-generated by icon.tsx and apple-icon.tsx
  // Additional static icons in /public folder

  // Alternate links
  alternates: {
    canonical: SITE_URL,
    languages: {
      "en-US": SITE_URL,
      "x-default": SITE_URL,
    },
  },

  // App links
  appleWebApp: {
    capable: true,
    statusBarStyle: "black-translucent",
    title: SITE_NAME,
  },

  // Other
  other: {
    "msapplication-TileColor": "#020617",
    "msapplication-config": "/browserconfig.xml",
    "apple-mobile-web-app-capable": "yes",
    "mobile-web-app-capable": "yes",
  },
};

// JSON-LD Structured Data
const jsonLd = {
  "@context": "https://schema.org",
  "@graph": [
    // WebSite Schema
    {
      "@type": "WebSite",
      "@id": `${SITE_URL}/#website`,
      url: SITE_URL,
      name: SITE_NAME,
      description: SITE_DESCRIPTION,
      publisher: {
        "@id": `${SITE_URL}/#organization`,
      },
      potentialAction: [
        {
          "@type": "SearchAction",
          target: {
            "@type": "EntryPoint",
            urlTemplate: `${SITE_URL}/?search={search_term_string}`,
          },
          "query-input": "required name=search_term_string",
        },
      ],
      inLanguage: "en-US",
    },
    // Organization Schema
    {
      "@type": "Organization",
      "@id": `${SITE_URL}/#organization`,
      name: SITE_NAME,
      url: SITE_URL,
      logo: {
        "@type": "ImageObject",
        "@id": `${SITE_URL}/#logo`,
        inLanguage: "en-US",
        url: `${SITE_URL}/logo.png`,
        contentUrl: `${SITE_URL}/logo.png`,
        width: 512,
        height: 512,
        caption: SITE_NAME,
      },
      image: {
        "@id": `${SITE_URL}/#logo`,
      },
      sameAs: [
        "https://twitter.com/geonarrator",
        "https://github.com/geonarrator",
        "https://linkedin.com/company/geonarrator",
      ],
    },
    // WebApplication Schema
    {
      "@type": "WebApplication",
      "@id": `${SITE_URL}/#webapp`,
      name: SITE_NAME,
      description: SITE_DESCRIPTION,
      url: SITE_URL,
      applicationCategory: "DesignApplication",
      operatingSystem: "Any",
      browserRequirements: "Requires JavaScript. Requires HTML5.",
      softwareVersion: "1.0.0",
      offers: {
        "@type": "Offer",
        price: "0",
        priceCurrency: "USD",
      },
      featureList: [
        "3D map visualization",
        "Scrollytelling editor",
        "Drag-and-drop scene management",
        "Cinematic camera controls",
        "Real-time preview",
        "Export to JSON",
        "No-code interface",
        "Mapbox GL integration",
      ],
      screenshot: `${SITE_URL}/og-image.png`,
      aggregateRating: {
        "@type": "AggregateRating",
        ratingValue: "4.8",
        ratingCount: "127",
        bestRating: "5",
        worstRating: "1",
      },
    },
    // SoftwareApplication Schema (for app stores)
    {
      "@type": "SoftwareApplication",
      name: SITE_NAME,
      description: SITE_DESCRIPTION,
      applicationCategory: "MultimediaApplication",
      operatingSystem: "Web Browser",
      offers: {
        "@type": "Offer",
        price: "0",
        priceCurrency: "USD",
      },
    },
    // FAQPage Schema
    {
      "@type": "FAQPage",
      "@id": `${SITE_URL}/#faq`,
      mainEntity: [
        {
          "@type": "Question",
          name: "What is GeoNarrator Studio?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "GeoNarrator Studio is a no-code 3D scrollytelling map editor that allows you to create stunning map-based stories without writing code. It uses Mapbox GL for beautiful 3D maps with cinematic camera controls.",
          },
        },
        {
          "@type": "Question",
          name: "Is GeoNarrator Studio free to use?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "Yes, GeoNarrator Studio is free to use. You can create, edit, and export your stories without any cost. You'll need your own Mapbox API key for the maps.",
          },
        },
        {
          "@type": "Question",
          name: "What can I create with GeoNarrator Studio?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "You can create interactive scrollytelling experiences with 3D maps. Perfect for journalism, education, travel stories, historical narratives, and data visualization projects.",
          },
        },
        {
          "@type": "Question",
          name: "Do I need coding skills to use GeoNarrator Studio?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "No coding skills are required. GeoNarrator Studio provides a visual drag-and-drop interface for creating stories. Simply add scenes, position the camera, and write your narrative.",
          },
        },
      ],
    },
    // BreadcrumbList Schema
    {
      "@type": "BreadcrumbList",
      "@id": `${SITE_URL}/#breadcrumb`,
      itemListElement: [
        {
          "@type": "ListItem",
          position: 1,
          name: "Home",
          item: SITE_URL,
        },
      ],
    },
    // CreativeWork Schema
    {
      "@type": "CreativeWork",
      "@id": `${SITE_URL}/#creativework`,
      name: SITE_NAME,
      description: SITE_DESCRIPTION,
      url: SITE_URL,
      author: {
        "@id": `${SITE_URL}/#organization`,
      },
      creator: {
        "@id": `${SITE_URL}/#organization`,
      },
      keywords: "scrollytelling, 3D maps, mapbox, storytelling, no-code, map editor, interactive maps",
      inLanguage: "en-US",
      isAccessibleForFree: true,
      license: "https://creativecommons.org/licenses/by/4.0/",
    },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark" dir="ltr">
      <head>
        {/* JSON-LD Structured Data */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />
        {/* Preconnect to external resources */}
        <link rel="preconnect" href="https://api.mapbox.com" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        {/* DNS Prefetch */}
        <link rel="dns-prefetch" href="https://api.mapbox.com" />
        <link rel="dns-prefetch" href="https://events.mapbox.com" />
      </head>
      <body
        className={`${inter.variable} ${jetbrainsMono.variable} antialiased bg-slate-950 text-slate-100`}
      >
        {children}
      </body>
    </html>
  );
}
